name: Auto Build & Release APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"   # 关键修复点！！
          cache: true

      - name: Flutter Pub Get
        working-directory: simple_live_app
        run: flutter pub get

      - name: Build APK
        working-directory: simple_live_app
        run: flutter build apk --release --split-per-abi

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.run_number }}"
          name: "Auto Release ${{ github.run_number }}"
          artifacts: |
            simple_live_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
